// Generated by scripts/generate-verifier-policy.py from the untracked RP access certificate.
// Do not put RP private keys, access certificates, or registration certificates in Git.
public enum IIRYGeneratedVerifierPolicy {
    public static let acceptableAudiences: [String] = ["x509_hash:0YSSQqY0Pg5qEuWqNReqZh55E50lCLoMVO7tQyomxtw"]
}
