#!/usr/bin/env python3
from __future__ import annotations

import argparse
import base64
import hashlib
from pathlib import Path


ROOT = Path(__file__).resolve().parents[1]
DEFAULT_CERT = ROOT / "service/secrets/access-certificate.pem"
DEFAULT_OUTPUT = ROOT / "ios/IIRY.swiftpm/Sources/IIRYCore/VerifierPolicy.generated.swift"


def certificate_der(path: Path) -> bytes | None:
    if not path.exists():
        return None
    data = path.read_bytes()
    try:
        text = data.decode("utf-8")
    except UnicodeDecodeError:
        return data
    if "-----BEGIN CERTIFICATE-----" not in text:
        return data
    body = "".join(line.strip() for line in text.splitlines() if not line.startswith("-----"))
    return base64.b64decode(body)


def x509_hash_audience(der: bytes) -> str:
    digest = hashlib.sha256(der).digest()
    value = base64.urlsafe_b64encode(digest).decode("ascii").rstrip("=")
    return f"x509_hash:{value}"


def swift_source(audiences: list[str]) -> str:
    entries = ", ".join(f'"{audience}"' for audience in audiences)
    return (
        "// Generated by scripts/generate-verifier-policy.py from the untracked RP access certificate.\n"
        "// Do not put RP private keys, access certificates, or registration certificates in Git.\n"
        "public enum IIRYGeneratedVerifierPolicy {\n"
        f"    public static let acceptableAudiences: [String] = [{entries}]\n"
        "}\n"
    )


def main() -> None:
    parser = argparse.ArgumentParser(description="Generate Swift verifier audience policy from the local RP access certificate.")
    parser.add_argument("--access-cert", type=Path, default=DEFAULT_CERT)
    parser.add_argument("--out", type=Path, default=DEFAULT_OUTPUT)
    args = parser.parse_args()

    der = certificate_der(args.access_cert)
    audiences = [x509_hash_audience(der)] if der else []
    output = swift_source(audiences)
    args.out.parent.mkdir(parents=True, exist_ok=True)
    if args.out.exists() and args.out.read_text() == output:
        return
    args.out.write_text(output)


if __name__ == "__main__":
    main()
